import assert from 'node:assert/strict';
import { freshState, restoreState, care, chat, friendship, dayKey } from '../model.js';
import { chatReply, topics, followup, memoryDefinitions } from '../journey.js';
const now = new Date(2026, 9, 5, 12).getTime();
const stranger = freshState(now);
const untouched = JSON.stringify(stranger);
assert.equal(chat(stranger, 'day', 'good', now).ok, false);
assert.equal(JSON.stringify(stranger), untouched, '陌生人不能通过聊天选择绕过阶段');
assert.deepEqual(care(stranger, 'greet', 0, now).storyStages, [1]);
assert.deepEqual(care(stranger, 'greet', 0, now + 3000).storyStages, []);
assert.deepEqual(care(stranger, 'greet', 0, now + 6000).storyStages, [2]);
assert.deepEqual(stranger.journey.memories.map(m => m.id), ['hello', 'stage-2']);
const beforeInvalid = JSON.stringify(stranger);
assert.equal(chat(stranger, 'day', 'not-a-choice', now + 9000).ok, false);
assert.equal(JSON.stringify(stranger), beforeInvalid, '无效回答不发奖励、不写回忆');
const result = chat(stranger, 'day', 'tired', now + 9000);
assert.equal(result.ok, true); assert.equal(stranger.xp, 26);
assert.equal(result.reply, chatReply(2, 'day', 'tired'));
assert.equal(stranger.journey.memories.at(-1).id, 'chat-day');
chat(stranger, 'day', 'good', now + 12000);
assert.equal(stranger.journey.memories.filter(m => m.id === 'chat-day').length, 1);
const thirdChat = chat(stranger, 'quiet', 'stay', now + 15000);
assert.equal(friendship(stranger.xp).level, 3);
assert.deepEqual(thirdChat.storyStages, [3]);
assert.equal(thirdChat.reply, chatReply(2, 'quiet', 'stay'), '本句使用回答前的关系语气');
const restored = restoreState(JSON.parse(JSON.stringify(stranger)), now + 16000);
assert.deepEqual(restored.journey, stranger.journey, '刷新保留回忆、日期及最近回答');
assert.equal(followup(restored, 3, dayKey(now + 16000)), null, '当天不反复追问');
assert.match(followup(restored, 3, dayKey(now + 86400000)), /窗边/);
restored.journey.followupDay = dayKey(now + 86400000);
assert.equal(followup(restored, 3, dayKey(now + 86400000)), null, '同一天仅一次续聊');
const tired = freshState(now); tired.xp = 42;
chat(tired, 'day', 'tired', now);
assert.match(followup(tired, 3, dayKey(now + 86400000)), /好一点/);
assert.match(followup(tired, 5, dayKey(now + 86400000)), /椅子还给你留着/);
for (let level = 2; level <= 5; level++) for (const topic of topics) for (const choice of topic.choices) assert.equal(typeof chatReply(level, topic.id, choice.id), 'string');
const legacyRaw = { ...freshState(now - 86400000), xp: 100, coins: 33, name: '奶糖' }; delete legacyRaw.journey;
const legacy = restoreState(legacyRaw, now);
assert.equal(legacy.xp, 100); assert.equal(legacy.coins, 33); assert.equal(legacy.name, '奶糖');
assert.equal(legacy.daily.stage, 5, '旧存档跨日按当前关系安排心愿');
assert.deepEqual(legacy.journey.memories, [], '旧存档不伪造历史事件');
assert.deepEqual(care(legacy, 'pet', 0, now).storyStages, []);
assert.deepEqual(legacy.journey.memories.map(m => m.id), ['pet']);
care(legacy, 'pet', 0, now + 1000);
assert.equal(legacy.journey.memories.length, 1);
legacy.sleeping = true;
const sleepingBefore = JSON.stringify(legacy);
assert.equal(chat(legacy, 'day', 'good', now + 2000).ok, false);
assert.equal(JSON.stringify(legacy), sleepingBefore, '睡眠中聊天不修改状态或记忆');
care(legacy, 'sleep', 0, now + 3000);
assert.equal(legacy.journey.memories.some(m => m.id === 'sleep'), false, '叫醒不冒充陪伴入睡');
care(legacy, 'sleep', 0, now + 4000);
assert.equal(legacy.journey.memories.at(-1).id, 'sleep');
const skip = freshState(now); skip.xp = 18;
assert.deepEqual(care(skip, 'play', 25, now).storyStages, [3, 4], '跳过多个阶段时逐页记录');
const bad = restoreState({ ...freshState(now), journey: { memories: [null, { id: 'unknown', at: now }, { id: 'pet', at: now + 1 }, { id: 'hello', at: now }, { id: 'hello', at: now }, { id: '__proto__', at: now }], lastChat: { topic: 'day', choice: 'invalid', at: now }, followupDay: '<script>' } }, now);
assert.deepEqual(bad.journey.memories, [{ id: 'hello', at: now }]);
assert.equal(bad.journey.lastChat, null); assert.equal(bad.journey.followupDay, '');
assert.ok(Object.keys(memoryDefinitions).length < 20, '回忆有限且去重，不随重复点击膨胀');
console.log('聊天权限、分支语气、阶段剧情、回忆去重、旧存档兼容、跨日续聊、睡眠与损坏字段检查通过。');
