import assert from 'node:assert/strict';
import { freshState, restoreState, care, applyElapsed, friendship, canInteract, dailyPlan } from '../model.js';
const now = new Date(2026, 9, 3, 12).getTime();
assert.equal(freshState(now).name, '啵啵');
const renamed = restoreState({ ...freshState(now), name: '小糯', xp: 65, coins: 35 }, now);
assert.equal(renamed.name, '啵啵');
assert.equal(renamed.xp, 65); assert.equal(renamed.coins, 35);
assert.equal(restoreState({ ...freshState(now), name: '奶糖' }, now).name, '奶糖', '改名不覆盖已有自定义名字');
const state = freshState(now);
for (const action of ['pet', 'feed', 'gift', 'wash', 'sleep', 'play']) {
  const before = JSON.stringify(state);
  assert.equal(care(state, action).ok, false, `陌生人阶段不能 ${action}`);
  assert.equal(JSON.stringify(state), before, '拒绝的动作不能改变状态或亲密度');
}
assert.deepEqual(dailyPlan(state).map(p => p.key), ['greet']);
for (let i = 0; i < 2; i++) care(state, 'greet');
assert.equal(care(state, 'greet').dailyReward, true);
assert.equal(state.coins, 20);
assert.equal(state.xp, 18); assert.equal(friendship(state.xp).title, '点头之交', '3 次打招呼进入下一阶段');
assert.equal(canInteract(state, 'play').ok, true);
assert.equal(canInteract(state, 'feed').ok, false);
assert.equal(canInteract(state, 'pet').ok, false);
assert.equal(care(state, 'greet').dailyReward, false);
assert.equal(state.coins, 20, '打招呼不能重复领每日奖励');
for (let i = 0; i < 2; i++) care(state, 'greet');
assert.equal(state.xp, 42); assert.equal(friendship(state.xp).title, '逐渐熟悉', '再聊 3 次进入下一阶段');
assert.equal(canInteract(state, 'feed').ok, true);
assert.equal(canInteract(state, 'gift').ok, true);
assert.equal(canInteract(state, 'sleep').ok, true);
assert.equal(canInteract(state, 'pet').ok, false);
state.xp = 65; assert.equal(canInteract(state, 'pet').ok, false);
state.xp = 66;
assert.equal(canInteract(state, 'pet').ok, true); assert.equal(canInteract(state, 'wash').ok, false);
const washBoundary = freshState(now); washBoundary.xp = 89;
const beforeWash = JSON.stringify(washBoundary);
assert.equal(care(washBoundary, 'wash').ok, false, 'Lv. 4 还不能洗香香');
assert.equal(JSON.stringify(washBoundary), beforeWash, '被拒绝的洗香香不能改变状态');
washBoundary.xp = 90;
assert.equal(care(washBoundary, 'wash').ok, true, 'Lv. 5 才开放洗香香');
assert.equal(washBoundary.energy, 88); assert.equal(washBoundary.xp, 96);
state.daily.stage = 4; state.daily.claimed = false;
care(state, 'feed'); assert.equal(state.food, 95);
care(state, 'feed'); assert.equal(state.food, 100);
assert.equal(care(state, 'feed').ok, false);
for (let i = 0; i < 5; i++) care(state, 'pet');
const reward = care(state, 'play', 10);
assert.equal(reward.dailyReward, true);
const coins = state.coins;
care(state, 'pet'); assert.equal(state.coins, coins + 1, '每日奖励不能重复领取');
care(state, 'sleep');
const previousXP = state.xp;
assert.equal(care(state, 'pet').ok, false);
assert.equal(state.xp, previousXP, '睡觉时不应继续获得摸摸奖励');
state.energy = 30; applyElapsed(state, now + 5 * 60000);
assert.equal(state.energy, 50, '睡眠按实际时间恢复元气');
const saved = restoreState(JSON.parse(JSON.stringify(state)), now + 10 * 60000);
assert.equal(saved.sleeping, true); assert.equal(saved.energy, 70);
applyElapsed(saved, now + 86400000);
assert.equal(saved.daily.pet, 0); assert.equal(saved.daily.claimed, false);
assert.equal(saved.energy, 100);
const corrupt = restoreState({ version: 1, name: '<script>x</script>', food: -900, joy: 'invalid', energy: Infinity, xp: 'bad', daily: null }, now);
assert.equal(corrupt.food, 20); assert.equal(corrupt.joy, 80); assert.equal(corrupt.energy, 90); assert.equal(corrupt.xp, 0);
assert.equal(Array.from(corrupt.name).length, 12);
for (const [xp, level] of [[0, 1], [17, 1], [18, 2], [41, 2], [42, 3], [65, 3], [66, 4], [89, 4], [90, 5]]) assert.equal(friendship(xp).level, level);
const fastProgress = freshState(now);
for (let expected = 2; expected <= 5; expected++) {
  for (let i = 0; i < 3; i++) care(fastProgress, 'greet');
  assert.equal(friendship(fastProgress.xp).level, expected, '每阶段只需 3 次有效招呼或聊天');
}
const offline = freshState(now); applyElapsed(offline, now + 30 * 86400000);
assert.equal(offline.food, 51); assert.equal(offline.joy, 62); assert.equal(offline.energy, 70);
const poor = freshState(now); poor.xp = 42; assert.equal(care(poor, 'gift').ok, false); assert.equal(poor.coins, 0);
poor.energy = 29; assert.equal(care(poor, 'play', 10).ok, false);
const legacySleeper = freshState(now); legacySleeper.sleeping = true;
assert.equal(care(legacySleeper, 'greet').ok, false);
assert.equal(care(legacySleeper, 'sleep').ok, true, '旧低等级睡眠存档仍能叫醒，避免无法继续打招呼');
assert.equal(legacySleeper.sleeping, false);
console.log('陌生人限制、逐级解锁、拒绝动作无副作用、打招呼奖励、旧存档恢复、睡眠、每日奖励、离线衰减检查通过。');
