import assert from 'node:assert/strict';
import { freshState, restoreState, care, applyElapsed, friendship } from '../model.js';
const now = new Date(2026, 9, 3, 12).getTime();
const state = freshState(now);
care(state, 'feed'); assert.equal(state.food, 95);
care(state, 'feed'); assert.equal(state.food, 100);
assert.equal(care(state, 'feed').ok, false);
for (let i = 0; i < 5; i++) care(state, 'pet');
const reward = care(state, 'play', 10);
assert.equal(reward.dailyReward, true);
const coins = state.coins;
care(state, 'pet'); assert.equal(state.coins, coins + 1, '每日奖励不能重复领取');
care(state, 'sleep');
const previousXP = state.xp;
assert.equal(care(state, 'pet').ok, false);
assert.equal(state.xp, previousXP, '睡觉时不应继续获得摸摸奖励');
state.energy = 30; applyElapsed(state, now + 5 * 60000);
assert.equal(state.energy, 50, '睡眠按实际时间恢复元气');
const saved = restoreState(JSON.parse(JSON.stringify(state)), now + 10 * 60000);
assert.equal(saved.sleeping, true); assert.equal(saved.energy, 70);
applyElapsed(saved, now + 86400000);
assert.equal(saved.daily.pet, 0); assert.equal(saved.daily.claimed, false);
assert.equal(saved.energy, 100);
const corrupt = restoreState({ version: 1, name: '<script>x</script>', food: -900, joy: 'invalid', energy: Infinity, xp: 'bad', daily: null }, now);
assert.equal(corrupt.food, 20); assert.equal(corrupt.joy, 80); assert.equal(corrupt.energy, 90); assert.equal(corrupt.xp, 0);
assert.equal(Array.from(corrupt.name).length, 12);
assert.equal(friendship(59).level, 1); assert.equal(friendship(60).level, 2); assert.equal(friendship(150).level, 3);
const offline = freshState(now); applyElapsed(offline, now + 30 * 86400000);
assert.equal(offline.food, 51); assert.equal(offline.joy, 62); assert.equal(offline.energy, 70);
const poor = freshState(now); assert.equal(care(poor, 'gift').ok, false); assert.equal(poor.coins, 0);
poor.energy = 29; assert.equal(care(poor, 'play', 10).ok, false);
console.log('状态、睡眠、存档恢复、每日奖励、离线衰减、升级与礼物检查通过。');
